export class ErrorCodes {
    //Service
    static TRACK_NOT_FOUND = "TRACK_NOT_FOUND";
    static FAILED_TO_UPDATE_TRACK = "FAILED_TO_UPDATE_TRACK";
    static ACCESS_DENIED = "ACCESS_DENIED";
    static VALIDATION_ERROR = "VALIDATION_ERROR";

    //Api
    static FAILED_TO_FETCH_TRACK_METADATA = "FAILED_TO_FETCH_TRACK_METADATA";

    //Database error
    static FAILED_TO_INSERT_TRACKS = "FAILED_TO_INSERT_TRACKS";
    static FAILED_TO_DELETE_TRACK = "FAILED_TO_DELETE_TRACK";
    static FAILED_TO_GET_TRACKS = "FAILED_TO_GET_TRACKS";
    static FAILED_TO_GET_TRACK = "FAILED_TO_GET_TRACK";
}
