class ErrorCodes {
    //Resolver
    static TRACK_NOT_FOUND = "TRACK_NOT_FOUND";
    static FAILED_TO_UPDATE_TRACK = "FAILED_TO_UPDATE_TRACK";
    static FAILED_TO_GET_TRACK = "FAILED_TO_GET_TRACK";
    static FAILED_TO_GET_TRACKS = "FAILED_TO_GET_TRACKS";
    static FAILED_TO_DELETE_TRACK = "FAILED_TO_DELETE_TRACK";
    static ACCESS_DENIED = "ACCESS_DENIED";

    //Api
    static FAILED_TO_FETCH_TRACK_METADATA = "FAILED_TO_FETCH_TRACK_METADATA";

}
  
module.exports = ErrorCodes;